// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onapxxjqygvokkaciigb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uYXB4eGpxeWd2b2trYWNpaWdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NzQzMzUsImV4cCI6MjA2MzU1MDMzNX0.SjlswYZSRbBb0h1A072QmhJ_byayGy6FX4adMlX0_vE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);